package:
  name: squeezemeta-dev
  version: "1.7.0.alpha3"

source:
  git_url: https://github.com/jtamames/squeezemeta.git
  git_tag: binonly

requirements:
  build:
    - python==3.10
    - r-base==4.1.3
    - r-ggplot2
    - r-reshape2
    - r-doMC
    - r-data.table
    - bioconductor-pathview
    - perl=5.26
    - perl-app-cpanminus
    - setuptools
    - cython >=0.19.1
    - numpy >=1.9.0
    - scipy >=0.12.0
    - pandas >=0.11.0
    - biopython >=1.62b
    - scikit-learn >=0.18.0
    - nose >=1.3.0
    - gsl
    - openmp
    - samtools
    - blas=*=mkl # To avoid openmp
    - readline=8
    - pydantic >=1.9.2,<2.0a1 # Add gtdb-tk, mOTUlizer and superpang python reqs in build
    - tqdm >=4.35.0           #  since they will be installed with pip but we'd rather have their deps installed through conda
    - dendropy >=4.1.0
    - graph-tool
    - mappy
    - python-igraph
      #- igraph==0.10.8 # Required by mOTUlizer but missing in conda apparently
  run:
    # Packages originally specified in the template
    - python==3.10.8
    - setuptools==68.2.2
    - cython >=0.19.1
    - numpy==1.26.0
    - scipy >=0.12.0
    - pandas >=0.11.0
    - biopython >=1.62b
    - scikit-learn >=0.18.0
    - nose >=1.3.0
    - gsl # last time I checked we need v2.7 from conda-forge (the one from anaconda will fail)
    - openmp==8.0.1
    - samtools==1.17
    - blas==1.0
    - future==0.18.3
    - matplotlib==3.8.0
    - dendropy >=4.1.0
    - pysam==0.20.0
    - biopython==1.81
    - perl==5.26.2
    - perl-tie-ixhash==1.23
    - perl-dbd-mysql==4.046
    - perl-dbd-sqlite==1.64
    - perl-lwp-simple==6.15
    - perl-xml-libxml==2.0132
    - perl-xml-parser==2.44_01
    - openjdk==17.0.3
    - ruby==2.5.1
    - r-base==4.1.3
    - r-ggplot2==3.4.2
    - r-reshape2==1.4.4
    - r-doMC
    - r-data.table==1.14.8
    - bioconductor-pathview==1.34.0
    - tree==2.1.1
    - readline==8.2
    - krona==2.8.1
    - spades==3.15.5
    - mothur==1.47.0
    - kmer-db==1.11.1
    - metabat2==2.15
    - pplacer==1.1.alpha19
    - prodigal==2.6.3
    - pydantic >=1.9.2,<2.0a1
    - mash==2.3
    - fastani==1.34
    - libopenblas==0.3.24
    - fasttree==2.1.11
    - hmmer==3.3.2
    - tqdm >=4.35.0
    - graph-tool==2.45
    - minimap2==2.26
    - mappy==2.26
    #- igraph==0.10.8 # Required by mOTUlizer but missing in conda apparently, should get installed during build
    - python-igraph==0.10.2
    - nextflow==23.04.3
    # Extra dependencies
    - _sysroot_linux-64_curr_repodata_hack==3
    - arpack==3.7.0
    - at-spi2-atk==2.38.0
    - at-spi2-core==2.40.3
    - atk-1.0==2.38.0
    - attr==2.5.1
    - bioconductor-annotationdbi==1.56.2
    - bioconductor-biobase==2.54.0
    - bioconductor-biocgenerics==0.40.0
    - bioconductor-biostrings==2.62.0
    - bioconductor-genomeinfodb==1.30.1
    - bioconductor-genomeinfodbdata==1.2.7
    - bioconductor-graph==1.72.0
    - bioconductor-iranges==2.28.0
    - bioconductor-kegggraph==1.54.0
    - bioconductor-keggrest==1.34.0
    - bioconductor-org.hs.eg.db==3.14.0
    - bioconductor-rgraphviz==2.38.0
    - bioconductor-s4vectors==0.32.4
    - bioconductor-xvector==0.34.0
    - bioconductor-zlibbioc==1.40.0
    - blast-legacy==2.2.26
    - boost==1.74.0
    - boost-cpp==1.74.0
    - brotli==1.1.0
    - brotli-bin==1.1.0
    - bwidget==1.9.14
    - cairo==1.16.0
    - cairomm==1.14.4
    - cairomm-1.0==1.14.4
    - capnproto==0.10.2
    - cffi==1.15.1
    - colorama==0.4.6
    - concoct==1.1.0
    - contourpy==1.1.1
    - coreutils==9.4
    - cycler==0.11.0
    - cython==3.0.2
    - dendropy==4.6.1
    - epoxy==1.5.10
    - expat==2.5.0
    - fftw==3.3.10
    - font-ttf-dejavu-sans-mono==2.37
    - font-ttf-inconsolata==3.000
    - font-ttf-source-code-pro==2.038
    - font-ttf-ubuntu==0.83
    - fontconfig==2.14.2
    - fonts-conda-ecosystem==1
    - fonts-conda-forge==1
    - fonttools==4.42.1
    - freetype==2.12.1
    - fribidi==1.0.10
    - gdk-pixbuf==2.42.10
    - gettext==0.21.1
    - giflib==5.2.1
    - glpk==5.0
    - gmp==6.2.1
    - graph-tool-base==2.45
    - graphite2==1.3.14
    - gsl==2.7
    - gst-plugins-base==1.20.3
    - gstreamer==1.20.3
    - gtk3==3.24.35
    - gxx_impl_linux-64==13.2.0
    - harfbuzz==5.3.0
    - hdf5==1.10.6
    - hicolor-icon-theme==0.17
    - htslib==1.17
    - intel-openmp==2022.1.0
    - jack==1.9.21
    - joblib==1.3.2
    - jpeg==9e
    - k8==0.2.5
    - kernel-headers_linux-64==3.10.0
    - kiwisolver==1.4.5
    - lame==3.100
    - lcms2==2.14
    - ld_impl_linux-64==2.40
    - libblas==3.9.0
    - libbrotlicommon==1.1.0
    - libbrotlidec==1.1.0
    - libbrotlienc==1.1.0
    - libcap==2.66
    - libcblas==3.9.0
    - libclang==14.0.6
    - libclang13==14.0.6
    - libcups==2.3.3
    - libdb==6.2.32
    - libedit==3.1.20221030
    - libev==4.33
    - libevent==2.1.10
    - libexpat==2.5.0
    - libflac==1.4.3
    - libgcc-devel_linux-64==13.2.0
    - libgcc-ng==13.2.0
    - libgfortran-ng==13.2.0
    - libgfortran5==13.2.0
    - libgirepository==1.74.0
    - libglib==2.74.1
    - libgomp==13.2.0
    - libiconv==1.17
    - liblapack==3.9.0
    - libllvm14==14.0.6
    - libnghttp2==1.52.0
    - libnsl==2.0.0
    - libogg==1.3.5
    - libopus==1.3.1
    - libpng==1.6.39
    - librsvg==2.54.4
    - libsanitizer==13.2.0
    - libsndfile==1.1.0
    - libsqlite==3.43.0
    - libssh2==1.10.0
    - libstdcxx-devel_linux-64==13.2.0
    - libstdcxx-ng==13.2.0
    - libtiff==4.4.0
    - libtool==2.4.7
    - libudev1==253
    - libvorbis==1.3.7
    - libwebp==1.3.2
    - libwebp-base==1.3.2
    - libzlib==1.2.13
    - llvm-openmp==8.0.1
    - make==4.3
    - matplotlib-base==3.8.0
    - metis==5.1.0
    - mkl==2022.1.0
    - mpfr==4.2.0
    - mpg123==1.31.3
    - munkres==1.1.4
    - mysql-common==8.0.32
    - mysql-connector-c==6.1.11
    - mysql-libs==8.0.32
    - ncbi-vdb==3.0.8
    - ncurses==6.4
    - nose==1.3.7
    - nspr==4.35
    - nss==3.92
    - ossuuid==1.6.2
    - packaging==23.1
    - pandas==2.1.1
    - pango==1.50.12
    - pcre2==10.37
    - perl-app-cpanminus==1.7044
    - perl-business-isbn==3.004
    - perl-business-isbn-data==20140910.003
    - perl-carp==1.38
    - perl-constant==1.33
    - perl-data-dumper==2.173
    - perl-dbi==1.642
    - perl-encode==2.88
    - perl-encode-locale==1.05
    - perl-exporter==5.72
    - perl-extutils-makemaker==7.36
    - perl-file-path==2.16
    - perl-file-temp==0.2304
    - perl-mime-base64==3.15
    - perl-parent==0.236
    - perl-uri==1.76
    - perl-xml-namespacesupport==1.12
    - perl-xml-sax==1.02
    - perl-xml-sax-base==1.09
    - perl-xsloader==0.24
    - pillow==9.4.0
    - pip==23.2.1
    - pixman==0.40.0
    - ply==3.11
    - pthread-stubs==0.4
    - pulseaudio==14.0
    - pycairo==1.24.0
    - pycparser==2.21
    - pydantic==1.10.12
    - pygobject==3.44.1
    - pyparsing==3.1.1
    - pyqt==5.15.7
    - pyqt5-sip==12.11.0
    - python-dateutil==2.8.2
    - python-tzdata==2023.3
    - pytz==2023.3.post1
    - qt-main==5.15.6
    - r-askpass==1.1
    - r-bit==4.0.5
    - r-bit64==4.0.5
    - r-bitops==1.0_7
    - r-blob==1.2.4
    - r-cachem==1.0.8
    - r-cli==3.6.1
    - r-codetools==0.2_19
    - r-colorspace==2.1_0
    - r-cpp11==0.4.3
    - r-crayon==1.5.2
    - r-curl==4.3.3
    - r-dbi==1.1.3
    - r-domc==1.3.8
    - r-ellipsis==0.3.2
    - r-fansi==1.0.4
    - r-farver==2.1.1
    - r-fastmap==1.1.1
    - r-foreach==1.5.2
    - r-glue==1.6.2
    - r-gtable==0.3.3
    - r-httr==1.4.6
    - r-isoband==0.2.7
    - r-iterators==1.0.14
    - r-jsonlite==1.8.5
    - r-labeling==0.4.2
    - r-lattice==0.21_8
    - r-lifecycle==1.0.3
    - r-magrittr==2.0.3
    - r-mass==7.3_58.3
    - r-matrix==1.5_4.1
    - r-memoise==2.0.1
    - r-mgcv==1.8_42
    - r-mime==0.12
    - r-munsell==0.5.0
    - r-nlme==3.1_162
    - r-openssl==2.0.5
    - r-pillar==1.9.0
    - r-pkgconfig==2.0.3
    - r-plogr==0.2.0
    - r-plyr==1.8.8
    - r-png==0.1_8
    - r-r6==2.5.1
    - r-rcolorbrewer==1.1_3
    - r-rcpp==1.0.10
    - r-rcurl==1.98_1.12
    - r-rlang==1.1.1
    - r-rsqlite==2.3.1
    - r-scales==1.2.1
    - r-stringi==1.7.12
    - r-stringr==1.5.0
    - r-sys==3.4.2
    - r-tibble==3.2.1
    - r-utf8==1.2.3
    - r-vctrs==0.6.2
    - r-viridislite==0.4.1
    - r-withr==2.5.0
    - r-xml==3.99_0.11
    - scikit-learn==1.3.1
    - scipy==1.11.2
    - sed==4.8
    - seqtk==1.4
    - sigcpp-2.0==2.10.8
    - sip==6.7.11
    - six==1.16.0
    - sparsehash==2.0.4
    - sra-tools==3.0.8
    - suitesparse==5.10.1
    - tbb==2021.8.0
    - texttable==1.6.7
    - threadpoolctl==3.2.0
    - tk==8.6.12
    - tktable==2.10
    - toml==0.10.2
    - tomli==2.0.1
    - tornado==6.3.3
    - tqdm==4.66.1
    - typing-extensions==4.8.0
    - typing_extensions==4.8.0
    - tzdata==2023c
    - unicodedata2==15.0.0
    - vsearch==2.15.2
    - wheel==0.41.2
    - xcb-util==0.4.0
    - xcb-util-image==0.4.0
    - xcb-util-keysyms==0.4.0
    - xcb-util-renderutil==0.3.9
    - xcb-util-wm==0.4.1
    - xorg-fixesproto==5.0
    - xorg-inputproto==2.3.2
    - xorg-kbproto==1.0.7
    - xorg-libice==1.0.10
    - xorg-libsm==1.2.3
    - xorg-libx11==1.8.4
    - xorg-libxau==1.0.11
    - xorg-libxdmcp==1.1.3
    - xorg-libxext==1.3.4
    - xorg-libxfixes==5.0.3
    - xorg-libxi==1.7.10
    - xorg-libxrender==0.9.10
    - xorg-libxt==1.3.0
    - xorg-libxtst==1.2.3
    - xorg-recordproto==1.14.2
    - xorg-renderproto==0.11.1
    - xorg-xextproto==7.3.0
    - xorg-xproto==7.0.31
    - yaml==0.1.7
    - zlib==1.2.13
    - zstandard==0.21.0

build:
  noarch: generic

test:
  command: "cd $PREFIX/SqueezeMeta/scripts; for script in *.pl; do perl -c $script; done; perl $PREFIX/SqueezeMeta/utils/install_utils/test_install.pl"

about:
  home:  https://github.com/jtamames/SqueezeMeta
  license: GPL-3
  license_file: ../../LICENSE
  summary: 'SqueezeMeta: a fully automated metagenomics pipeline, from reads to bins'
  description:
          "SqueezeMeta is a fully automatic pipeline for metagenomics/metatranscriptomics,
          covering all steps of the analysis. SqueezeMeta includes multi-metagenome
          support allowing the co-assembly of related metagenomes and the retrieval of
          individual genomes via binning procedures.
          \n
          \n
          To install this package with mamba run:
          \n
          \n
          `mamba create -n SqueezeMeta -c conda-forge -c bioconda -c anaconda -c fpusan squeezemeta-dev --no-channel-priority`
          \n
          \n
          And activate it with:
          \n
          \n
          `conda activate SqueezeMeta`
          \n
          \n
          Detailed usage instructions can be found at <http://github.com/jtamames/SqueezeMeta>"
  dev_url: https://github.com/jtamames/SqueezeMeta
  doc_url: https://github.com/jtamames/SqueezeMeta
  doc_source_url: https://github.com/jtamames/SqueezeMeta/blob/master/README.md
  recipe-maintainers:
      - fpusan
